version: '0.1.{build}'
image: Visual Studio 2017
configuration: Release
environment:
  matrix:
    - DruidDotNetVersion: 0.1.{build}
build_script:
  - ps: .\build.ps1
artifacts:
  - path: .\artifacts\*.nupkg
assembly_info:
  account_feed: true 
  project_feed: true 
deploy: on