version: '0.1.{build}'
image: Visual Studio 2017
configuration: Release
environment:
  matrix:
    - DruidDotNetVersion: 0.1.{build}
build_script:
  - ps: .\build.ps1
artifacts:
  - path: .\artifacts\*.nupkg
deploy: on
dotnet_csproj:
  patch: true
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
skip_commits:
  files:
    - README.md